### PR TITLE
initial style

### PR DESCRIPTION
**Pull request by FomasTreeman**

### CODE REVIEW

**Review by cameochoquer — CHANGES_REQUESTED** [review]
Can we we re-arrange CSS so it's elements, then classes and keep it consistent? 
Also, re naming 'submit-button' is better than 'submit-b'

**Review by cameochoquer — CHANGES_REQUESTED** [review]
Small tweaks to be more BEM and avoid css snowballing: 

Buttons: 
  Color: inherit  
  background-color: transparent;
  border: none;
  cursor: pointer;
  font-size: 1.5rem;

submit button:
  margin-top: 1rem;

Create flex-column class
Create margin-top class

**Review by cameochoquer — APPROVED** [review]
looks tighter! 
I think I'm a bit more opinionated but would prefer full names rather than shortened/acronyms for classes column>col but I think others are probably cool with this!

**Comment by FomasTreeman** [comment]
Agreed, good advice, definitely easier to read. Abbreviations I get it, I think it's more for when the list of class names gets very long you want to be able to run through it a little quicker but I'm not miffed either way, just being lazy

**Pull request merged**
